[package]
name = "serde_arrow_repro"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "54.2"
bytes = "1.6.0"
parquet = "54.2"
serde = { version = "1.0.198", features = ["derive"] }
serde_arrow = { version = "0.13.1", features = ["arrow-54"] }
